// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAyIESdjjqKcG2yjZsyZ5iKD9LiMp-_T4o',
    appId: '1:933114366375:web:320134b3b9ea71d0dc0e82',
    messagingSenderId: '933114366375',
    projectId: 'news-kit-demo',
    authDomain: 'news-kit-demo.firebaseapp.com',
    storageBucket: 'news-kit-demo.firebasestorage.app',
    measurementId: 'G-Y3B6T4B2QM',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDeKFpZV30xzFZYEb5x7_tBhBqDcv_dzZA',
    appId: '1:933114366375:ios:63479ef605ac33cfdc0e82',
    messagingSenderId: '933114366375',
    projectId: 'news-kit-demo',
    storageBucket: 'news-kit-demo.firebasestorage.app',
    iosBundleId: 'com.example.newsUiKit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDeKFpZV30xzFZYEb5x7_tBhBqDcv_dzZA',
    appId: '1:933114366375:ios:63479ef605ac33cfdc0e82',
    messagingSenderId: '933114366375',
    projectId: 'news-kit-demo',
    storageBucket: 'news-kit-demo.firebasestorage.app',
    iosBundleId: 'com.example.newsUiKit',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAyIESdjjqKcG2yjZsyZ5iKD9LiMp-_T4o',
    appId: '1:933114366375:web:bb3dd42ab7639725dc0e82',
    messagingSenderId: '933114366375',
    projectId: 'news-kit-demo',
    authDomain: 'news-kit-demo.firebaseapp.com',
    storageBucket: 'news-kit-demo.firebasestorage.app',
    measurementId: 'G-N5D5WHJ9E7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBESFnxg983s7HOe1OQmEZlN1NXASWo0kg',
    appId: '1:933114366375:android:d530cb1aadfbccb5dc0e82',
    messagingSenderId: '933114366375',
    projectId: 'news-kit-demo',
    storageBucket: 'news-kit-demo.firebasestorage.app',
  );

}
