// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAOX2emKYSPpYpldqKwtEhjywuB71jCO28',
    appId: '1:23764328842:web:f8b16a9f1285c7d6e62873',
    messagingSenderId: '23764328842',
    projectId: 'news-ui-kit',
    authDomain: 'news-ui-kit.firebaseapp.com',
    storageBucket: 'news-ui-kit.firebasestorage.app',
    measurementId: 'G-73ZMNEK16H',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUIsRf-zCGs3YqGVTdeuYy_v66EH_nXy4',
    appId: '1:23764328842:ios:81cd02e5507af04fe62873',
    messagingSenderId: '23764328842',
    projectId: 'news-ui-kit',
    storageBucket: 'news-ui-kit.firebasestorage.app',
    iosBundleId: 'com.example.newsUiKit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCUIsRf-zCGs3YqGVTdeuYy_v66EH_nXy4',
    appId: '1:23764328842:ios:81cd02e5507af04fe62873',
    messagingSenderId: '23764328842',
    projectId: 'news-ui-kit',
    storageBucket: 'news-ui-kit.firebasestorage.app',
    iosBundleId: 'com.example.newsUiKit',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAOX2emKYSPpYpldqKwtEhjywuB71jCO28',
    appId: '1:23764328842:web:e6a6a6b5678b06dae62873',
    messagingSenderId: '23764328842',
    projectId: 'news-ui-kit',
    authDomain: 'news-ui-kit.firebaseapp.com',
    storageBucket: 'news-ui-kit.firebasestorage.app',
    measurementId: 'G-E2RHS13FQX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgXQWLyZn6_r0i1cgHQ95L1QNbsOyJius',
    appId: '1:23764328842:android:bd19718829883b35e62873',
    messagingSenderId: '23764328842',
    projectId: 'news-ui-kit',
    storageBucket: 'news-ui-kit.firebasestorage.app',
  );

}